### ISSUE TITLE
Add ~/Desktop support?

### ISSUE THREAD

**Issue by garymh** [fgr0/dmginstall#1]
First off: amazing extension! Is there a possibility to allow for a different folder than ~/Downloads though? For weirdos like me that download things straight to the desktop.

**Comment by fgr0** [comment]
Well its definitely possible :) and i even have some places in the code, which would allow this. 

I am not sure though, how to elegantly do this with a pure-alfred interface. I will definitely look into it (I abandoned this workflow for too long anyway), but currently busy with moving, so I can't give you any dates. But i guess sometime next week.

**Comment by garymh** [comment]
Sweet! :smiley:

**Comment by fgr0** [comment]
Finally - and i need to apologize for the long long delay - I managed to work again on the workflow, and now you can indeed specify alternative or _additional_ paths the workflow scans for installable objects.

Take a look at the updated README and if you have any questions, just ask.

**Comment by garymh** [comment]
Very cool! :thumbsup:
