### ISSUE TITLE
A better way of showing file types in Alfred's bar.

### ISSUE THREAD

**Issue by politicus** [fgr0/dmginstall#2]
Very nice workflow.

Could the file types be displayed right after the file name? 
For example: "install app_install (.alfredextension)"

I find it easier to read.

Thank you.

**Comment by fgr0** [comment]
It is a small enough change (one line), but i personally prefer it the way it currently is, so i am not going to change this repository.

If you are willing to change the workflow yourself, here is the line you would probably need to change:

In the file `alfred.py`, line 47

``` .py
            'title': "Install %s" % os.path.splitext(str(a))[0],
```

to

``` .py
            'title': "Install %s" % str(a),
```

If I had the time, i would integrate this as a setting, but I am not currently using Alfred---I am doing a lot of testing on the upcoming Yosemite release and have not installed Alfred on this computer. Thus, I am sad to say, that i have put this workflow on hold for the time being.

**Comment by politicus** [comment]
Just modified the code. 
Working pretty well.
Thank you very much.
